# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    driver: "gd"

    resolvers:
        default:
            web_path: ~

    cache:                default
    data_loader:          default
    default_image:        null
    twig:
        mode:             lazy

    controller:
        filter_action:          liip_imagine.controller:filterAction
        filter_runtime_action:  liip_imagine.controller:filterRuntimeAction
        redirect_response_code: 302

    filter_sets:
        cache: ~
        posts_thumbnail:
            quality: 75
            filters:
                thumbnail: {size: [250, 150], mode: outbound}
                upscale:
                    min: [250, 150]

        posts_blog:
            quality: 75
            filters:
                fixed:
                    width: 680
                    height: 240

        posts_popular:
            quality: 75
            filters:
                thumbnail: {size: [120, 70], mode: outbound}
                upscale:
                    min: [120, 70]

        categories_blog:
            quality: 75
            filters:
